<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InternetShop.Contract\InternetShop.Contract.csproj" />
    <ProjectReference Include="..\InternetShop.Data\InternetShop.Data.csproj" />
    <ProjectReference Include="..\InternetShop.Repositories\InternetShop.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

</Project>
